### ISSUE TITLE
Why JsonPathParser has default access modifier?

### ISSUE THREAD

**Issue by PiotrGravity** [gravity9-tech/json-patch-path#57]
`com.gravity9.jsonpatch.JsonPathParser` and its' method `parsePathToJsonPath` has been changed to default package access.
It was public in `com.github.java-json-tools`.
Can you make it public again? It makes migration to your fork unnecessarily complicated.

**Comment by piotr-bugara-gravity9** [comment]
We'll work on that.

**Comment by piotr-bugara-gravity9** [comment]
Done and released in version 2.0.1
