### ISSUE TITLE
Add operation overwrite previous value

### ISSUE THREAD

**Issue by GuanqunYang193** [gravity9-tech/json-patch-path#60]
In current implement, it seems if we add value to a pre-existed path, the old value will be overwrited. In order to identify the semantics of "add" and "update", should we check if the path already existed and throw exception.

**Comment by meehaws** [comment]
Indeed. That is the behaviour correct as described in Json Patch RFC 6902:

> [4.1](https://datatracker.ietf.org/doc/html/rfc6902#section-4.1).  
> 
> add
> 
>    The "add" operation performs one of the following functions,
>    depending upon what the target location references:
>  
>    o  If the target location specifies an object member that does exist,
>       that member's value is replaced.
> 

If you want to check if the path exists, you can use test operation and combine it with add:
[4.6 test operation](https://datatracker.ietf.org/doc/html/rfc6902#section-4.6)

**Comment by GuanqunYang193** [comment]
> Indeed. That is the behaviour correct as described in Json Patch RFC 6902:
> 
> > [4.1](https://datatracker.ietf.org/doc/html/rfc6902#section-4.1).
> > add
> > The "add" operation performs one of the following functions,
> > depending upon what the target location references:
> > o  If the target location specifies an object member that does exist,
> > that member's value is replaced.
> 
> If you want to check if the path exists, you can use test operation and combine it with add: [4.6 test operation](https://datatracker.ietf.org/doc/html/rfc6902#section-4.6)

Brilliant! Thanks!
