### ISSUE TITLE
Expose operations in JsonPatch class

### ISSUE THREAD

**Issue by GuanqunYang193** [gravity9-tech/json-patch-path#63]
Is it a good idea to expose the ```List<JsonPatchOperation> operations;``` in JsonPatch class so that users are able to iterate the list to do more check before apply the patch? Right now we can only visit the list using reflection. 

Why not check before JsonPatch Object is built? Check and iterate the bare JsonNode is not that convenient since redundant syntactical check needs to be done, which is already covered by the package.

Willing to submit a PR for this change.

**Comment by piotrlg9** [comment]
Operations field is accessible via getOperations() method. What is missing?

**Comment by GuanqunYang193** [comment]
> Operations field is accessible via getOperations() method. What is missing?

sorry, wrong from my ide side.
